// 15 authors
const authors = [
  {
    id: 1,
    name: "Alfonso Boggs",
    university_id: 4,
    date_of_birth: "1977-01-02",
    h_index: 113,
    gender: "Male",
  },
  {
    id: 2,
    name: "Jenifer Cussins",
    university_id: 5,
    date_of_birth: "1975-02-27",
    h_index: 58,
    gender: "Female",
  },
  {
    id: 3,
    name: "Jim Leathlay",
    university_id: 6,
    date_of_birth: "1985-08-25",
    h_index: 48,
    gender: "Male",
  },
  {
    id: 4,
    name: "Pip Enoksson",
    university_id: 1,
    date_of_birth: "1987-11-18",
    h_index: 60,
    gender: "Male",
  },
  {
    id: 5,
    name: "Maud Hudd",
    university_id: 7,
    date_of_birth: "1976-12-04",
    h_index: 36,
    gender: "Female",
  },
  {
    id: 6,
    name: "Krystyna Raiker",
    university_id: 7,
    date_of_birth: "1983-07-21",
    h_index: 19,
    gender: "Female",
  },
  {
    id: 7,
    name: "Stillman Gailor",
    university_id: 5,
    date_of_birth: "1975-03-02",
    h_index: 38,
    gender: "Male",
  },
  {
    id: 8,
    name: "Ebenezer Snowball",
    university_id: 8,
    date_of_birth: "1978-07-22",
    h_index: 110,
    gender: "Male",
  },
  {
    id: 9,
    name: "Alis Bolley",
    university_id: 6,
    date_of_birth: "1980-05-03",
    h_index: 118,
    gender: "Female",
  },
  {
    id: 10,
    name: "Avie Halston",
    university_id: 3,
    date_of_birth: "1979-06-03",
    h_index: 79,
    gender: "Female",
  },
  {
    id: 11,
    name: "Celesta Roddell",
    university_id: 1,
    date_of_birth: "1981-04-08",
    h_index: 4,
    gender: "Female",
  },
  {
    id: 12,
    name: "Ilaire Antusch",
    university_id: 6,
    date_of_birth: "1974-01-17",
    h_index: 93,
    gender: "Male",
  },
  {
    id: 13,
    name: "Glynis Rea",
    university_id: 4,
    date_of_birth: "1988-05-19",
    h_index: 54,
    gender: "Female",
  },
  {
    id: 14,
    name: "Fremont Lanchbury",
    university_id: 5,
    date_of_birth: "1983-03-14",
    h_index: 104,
    gender: "Non-binary",
  },
  {
    id: 15,
    name: "Kaja Iacovo",
    university_id: 5,
    date_of_birth: "1989-08-23",
    h_index: 77,
    gender: "Female",
  },
  {
    id: 16,
    name: "Bob Simple",
    university_id: 5,
    date_of_birth: "1990-08-12",
    h_index: 1,
    gender: "Male",
  },
];

export default authors;
