const steps = [
  { id: 1, desc: "Beat Cream Cheese" },
  { id: 2, desc: "Add condenced Milk and blend" },
  { id: 3, desc: "Add Lemon Juice and blend" },
  { id: 4, desc: "Add the mix to the pie crust" },
  { id: 5, desc: "Spead the Cherry Jam" },
  { id: 6, desc: "Place in refrigerator for 3h" },
  { id: 7, desc: "Preheat the oven" },
  { id: 8, desc: "Mix the ingredients in a bowl" },
  { id: 9, desc: "Spread the mix on baking sheet" },
  { id: 10, desc: "Bake for 30'" },
  { id: 11, desc: "Cook Macaroni for 8'" },
  { id: 12, desc: "Melt butter in a saucepan" },
  { id: 13, desc: "Add flour, salt, pepper and mix " },
  { id: 14, desc: "Add Milk and mix" },
  { id: 15, desc: "Cook until mix is smooth" },
  { id: 16, desc: "Add cheddar cheese" },
  { id: 17, desc: "Add the macaroni" },
  { id: 18, desc: "Beat the eggs" },
  { id: 19, desc: "Add soya sauce, sugar and salt" },
  { id: 20, desc: "Add oil to a sauce pan" },
  { id: 21, desc: "Bring to medium heat" },
  { id: 22, desc: "Add some mix to the sauce pan" },
  { id: 23, desc: "Let is cook for 1'" },
  { id: 24, desc: "Remove pan from fire" },
  { id: 25, desc: "Line two baking sheets with parchment paper" },
  {
    id: 26,
    desc: "Combine sugar, butter, cocoa powder and milk in a 2.5 – 3 quart sauce pan",
  },
  { id: 27, desc: "Set sauce pan over medium heat" },
  { id: 28, desc: "Cook and whisk frequently until it reaches a boil" },
  { id: 29, desc: "Stop stirring and let it boil for 1 minute" },
  { id: 30, desc: "Add in vanilla, peanut butter and oatmeal" },
  { id: 31, desc: "Stir to blend well" },
];

export default steps;
