const step_order = [
  { recipe_id: 1, step_index: 1, step_id: 1 },
  { recipe_id: 1, step_index: 2, step_id: 2 },
  { recipe_id: 1, step_index: 3, step_id: 3 },
  { recipe_id: 1, step_index: 4, step_id: 4 },
  { recipe_id: 1, step_index: 5, step_id: 5 },
  { recipe_id: 1, step_index: 6, step_id: 6 },
  { recipe_id: 2, step_index: 1, step_id: 7 },
  { recipe_id: 2, step_index: 2, step_id: 8 },
  { recipe_id: 2, step_index: 3, step_id: 9 },
  { recipe_id: 2, step_index: 4, step_id: 10 },
  { recipe_id: 3, step_index: 1, step_id: 11 },
  { recipe_id: 3, step_index: 2, step_id: 12 },
  { recipe_id: 3, step_index: 3, step_id: 13 },
  { recipe_id: 3, step_index: 4, step_id: 14 },
  { recipe_id: 3, step_index: 5, step_id: 15 },
  { recipe_id: 3, step_index: 6, step_id: 16 },
  { recipe_id: 3, step_index: 7, step_id: 17 },
  { recipe_id: 4, step_index: 1, step_id: 18 },
  { recipe_id: 4, step_index: 2, step_id: 19 },
  { recipe_id: 4, step_index: 3, step_id: 20 },
  { recipe_id: 4, step_index: 4, step_id: 21 },
  { recipe_id: 4, step_index: 5, step_id: 22 },
  { recipe_id: 4, step_index: 6, step_id: 23 },
  { recipe_id: 4, step_index: 7, step_id: 20 },
  { recipe_id: 4, step_index: 8, step_id: 22 },
  { recipe_id: 4, step_index: 9, step_id: 23 },
  { recipe_id: 4, step_index: 10, step_id: 24 },
  { recipe_id: 5, step_index: 1, step_id: 25 },
  { recipe_id: 5, step_index: 2, step_id: 26 },
  { recipe_id: 5, step_index: 3, step_id: 27 },
  { recipe_id: 5, step_index: 4, step_id: 28 },
  { recipe_id: 5, step_index: 5, step_id: 29 },
  { recipe_id: 5, step_index: 6, step_id: 24 },
  { recipe_id: 5, step_index: 7, step_id: 30 },
  { recipe_id: 5, step_index: 8, step_id: 31 },
];

export default step_order;
